### ISSUE TITLE
Adding Dictionaries to Aspell

### ISSUE THREAD

**Issue by acanyon** [Muscul/heroku-buildpack-aspell#1]
Aspell seams to be installed, but I'm having trouble importing dictionaries, and get the following error.

```
> `which aspell`
=> "vendor/aspell/bin/aspell\n"

> Spellchecker.check(@query, dictionary='en')
WARNING: Unable to enter Nroff mode: Unknown mode: "nroff".
Error: No word lists can be found for the language "en".
RuntimeError: Aspell command not found
```

Ideas? Would love to get this working on heroku! 

Please and thanks.
Alexa

**Comment by acanyon** [comment]
I solved this using a [fork](https://github.com/xavriley/heroku-buildpack-aspell) and setting `--dict-dir='/app/vendor/aspell/lib/aspell-0.60'"`

For Spellchecker gem:

```
Spellchecker.aspell_path = "/app/vendor/aspell/bin/aspell --data-dir='/app/vendor/aspell/lib/aspell-0.60' --dict-dir='/app/vendor/aspell/lib/aspell-0.60'"
```

**Comment by Muscul** [comment]
When you work with aspell on heroku, you need to specify the dictionary path. 
I use gem "ffi" for work with aspell, so dictionary path can be like this
`speller = FFI::Aspell::Speller.new("en_US", "dict-dir" => "/app/vendor/aspell/lib/aspell-0.60")`
